### ISSUE TITLE
Program crashes on launch on thumby

### ISSUE THREAD

**Issue by luigiamongus** [Timendus/thumby-silicon8#4]
I coped everything from the Silicon8 directory to my thumby, it flashes the title screen for less than a second and just reboots back the the thumby menu. Am I supposed to put the test files in there somewhere also?

**Comment by Timendus** [comment]
Hey there @luigiamongus! What do you mean by test files?

The trick should be to just copy everything that's in [this directory](https://github.com/Timendus/thumby-silicon8/tree/main/Games/Silicon8) to the directory `/Games/Silicon8` on your Thumby.

Please note though that I haven't received my physical Thumby yet, so I haven't been able to test on the real hardware yet. It could be that you have found a genuine bug 😉 Maybe you can check if there's an error in the IDE's MicroPython console when you try to run it?

**Comment by luigiamongus** [comment]
By test files I mean the files in playground. Also, I copied everything in the directory into the thumby editor and tried to run it in the emulator and it says, "ImportError: no module named 'thumbyinterface' " even though I copied thumbyinterface.py onto it

**Comment by Timendus** [comment]
Ah! No, you don't need the playground files. Those are not part of the application, just some snippets I used for development.

Is the `thumbyinterface.py` file in the same directory as the rest? Does it error on `Silicon8.py` line 29 or somewhere else? I'll take a look to see if everything still works on my end in the latest version of the emulator soon.

**Comment by Timendus** [comment]
It all still looks to be working fine in the emulator. But I see I have everything in the emulator's root, so yeah there could be an issue including stuff on the actual hardware. I'm not sure what to do about that until I receive my own unit, sorry!

**Comment by Timendus** [comment]
I moved the code to `/Games/Silicon8` on the emulator, and found that it broke with the exact error you mention. That issue has now been fixed, so it may also have been fixed on the real hardware too. Thanks for reporting it!

**Comment by Timendus** [comment]
There turned out to be a second issue: There's a `menu.py` in the Thumby's root and a second `menu.py` in `/Games/Silicon8`. The emulator doesn't have the former, so I didn't notice the issue before.

I changed the path so the second one gets a higher priority, and the thing now runs just fine on hardware! 🎉
