### ISSUE TITLE
.8o files?

### ISSUE THREAD

**Issue by slothstronomic** [Timendus/thumby-silicon8#6]
I found this software on the code.thumby.us website and want to run the game below. Can I do it?

[Game](https://internet-janitor.itch.io/super-neatboy)

**Comment by Timendus** [comment]
Hey there! I think I'll have to disappoint you. The game is an XO-CHIP game, which Silicon8 supports, and compiling `*.8o` files to `*.ch8` files is a piece of cake. But the resolution of the game is what they call "hires" and it uses 4 colour mode. So it has more pixels and more colours than the Thumby display has 😄

This limitation (and a few others) are documented here:

https://github.com/Timendus/thumby-silicon8#display-limitations

**Comment by Timendus** [comment]
(If you were just wondering how to go from a `*.8o` to a `*.ch8` file: 8o is short for "Octo", which is an IDE, assembler and emulator for CHIP-8 and friends. You can copy and paste the 8o file into it and either click run or "Save .ch8" under Toolbox > Binary tools. IDE here: https://johnearnest.github.io/Octo/)
